# Generated by Django 4.2.4 on 2023-09-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_login_register_password_alter_register_acc_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Amount',
            field=models.IntegerField(verbose_name='0'),
        ),
    ]
