# Generated by Django 4.2.4 on 2023-09-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_register_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='Acc_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='Acc_number',
            field=models.IntegerField(unique=True),
        ),
    ]
